f-droid: Add "android:" prefix and merge as needed
repology/repology-rules pull request #867
Opened 2024-09-30 19:41 UTC by Pandapip1

This will allow for comparing repositories that contain android packages, as well as allowing F-Droid's statistics (particularly https://github.com/repology/repology-updater/issues/1229 and current versions) to be correctly shown

2024-10-02 19:17 UTC, AMDmi3 requested changes
I'd retain the current ruleset structure, adding a flag (such as `addflag: android_ok`) instead of removing the package, and then excluding these from prefix rule (e.g. `setname: android:$0, noflag: android_ok`).

2024-10-02 21:33 UTC, Pandapip1 commented
Not sure I quite get what you meant. Is this closer to what you want?

2024-10-02 21:45 UTC, Pandapip1 commented
Done!

2024-10-03 12:53 UTC, AMDmi3 approved these changes

2024-10-03 12:53 UTC, merged