Merge servarr stack
repology/repology-rules pull request #869
Opened 2024-10-20 11:27 UTC by txtsd

It's my first time contributing in this repo.

I'm going to use `${servarr}` as a variable to denote any *arr app to explain what this PR aims to achieve.

`${servarr}` and `${servarr}-bin` should be the same version.
`${servarr}-devel` and `${servarr}-devel-bin` should be the same version, and they are development versions.
`${servarr}-nightly` and `${servarr}-nightly-bin` should be the same version, and they are also development versions.

Please let me know if my yaml-fu is correct, or if it needs changing~

2024-10-21 14:37 UTC, AMDmi3 requested changes
- Please don't put these into separate file, this makes it harder to look for rules. Rulest should be spread alphabetically.
- Please only merge names which are not currently merged. For instance, for `sonarr`, only `sonarr-develop` needs merging, not `sonarr-bin`, `sonarr-develop-bin`, `sonarr-nightly`, or `sonarr-nightly-bin`
- `-develop` and `-nighly` merges need `weak_devel: true, nolegacy: true` instead of `flavor`

2024-10-23 06:20 UTC, txtsd commented
Rules can be easily `grep`'d for. I didn't think that would be a problem.

Regardless, I'll make the changes!

2024-10-23 06:43 UTC, txtsd commented
Okay, ready for re-review!

2024-10-23 14:18 UTC, AMDmi3 requested changes
Like I've mentioned,
- You don't need flavors for nightly/develop. Note that you can also stick nightly and develop into the same rule where applicable.
- Please don't merge non-existing projects. Check project search first, if there's no e.g. `whisparr-nightly-bin`, rules should not mention it.

> EDIT: Are -bin packages automatically classified under their main project? If so, should I remove the -bin for sonarr?

This depends on repository. They are for aur but aren't for gentoo, and that rule is needed for gentoo, so no, please don't remove it.

2024-10-23 14:55 UTC, txtsd commented
The nighties and develops should be the same version each respectively though. Is that handled without flavors?

2024-10-23 15:09 UTC, AMDmi3 commented
> The nighties and develops should be the same version each respectively though. Is that handled without flavors?

Repology does not check version equivalence between packages. develop/develop-bin/nightly/nightly-bin will be handled independently, but the same way, ignored if version higher than release version and outdated if lower.

2024-10-24 09:42 UTC, txtsd commented
Okay, ready for review again!

The *-nightly packages on the AUR have been merged into *-nightly-bin, so there aren't any *-nightly, there are only *-nightly-bin now.

2024-10-24 10:46 UTC, txtsd commented
Rebased on master

2024-10-24 12:17 UTC, AMDmi3 requested changes
> - Please don't merge non-existing projects

This has not been fixed yet. See comments for examples.

2024-10-24 12:17 UTC, AMDmi3 commented on 800.renames-and-merges/p.yaml
> +- { setname: prowlarr,                 name: [$0-develop, $0-develop-bin, $0-nightly-bin], weak_devel: true, nolegacy: true }
https://repology.org/projects/?search=prowlarr
there is no `prowlarr-develop-bin` and no `prowlarr-nighly-bin`

2024-10-24 12:17 UTC, AMDmi3 commented on 800.renames-and-merges/l.yaml
> +- { setname: lidarr,                   name: [$0-develop, $0-develop-bin, $0-nightly-bin], weak_devel: true, nolegacy: true }
https://repology.org/projects/?search=lidarr
there is no `lidarr-develop-bin` and no `lidarr-nighly-bin`

2024-10-24 12:45 UTC, txtsd commented
Now it makes sense!

I was thinking in terms of packages, not projects.

I've got the hang of it now for future contributions!

Ready for (hopefully final) review~

2024-10-24 12:51 UTC, txtsd commented
Can you also show me how to mark some repositories' packages as develop?

For example in radarr, `Chocolatey`, `Gentoo`, and `LiGurOS develop` package the develop versions of radarr so the actual stable versions are shown as outdated.

2024-10-24 13:08 UTC, AMDmi3 approved these changes

2024-10-24 13:08 UTC, merged

2024-10-24 13:17 UTC, AMDmi3 commented
> Can you also show me how to mark some repositories' packages as develop?

We just [mark](https://github.com/repology/repology-rules/commit/39c5e6ef0258bd3a90a98259e4629eac81abedfa) these repositories as untrusted. Marking version range as devel is possible, but that would require regular manual updating of a rule, we don't want that.

2024-10-24 14:20 UTC, txtsd commented
Okay I'll open a new PR for the rest of the packages. Thanks for showing me how!

I'm the maintainer of `bazarr-beta`. I can guarantee it will always be beta.

Also, how often is the website updated?

2024-10-24 14:49 UTC, AMDmi3 commented
> Also, how often is the website updated?

Once each 4-5 hours.

2024-10-24 15:10 UTC, txtsd commented
I see `ruleset: liguros`, but I don't see a way to specifically target `LiGurOS Develop`.

2024-10-24 15:17 UTC, AMDmi3 commented
We just ban whole repository (which provides unstable version) untrusted, you don't need to specify versions for that.
And you can just use `ruleset: gentoo` which would affect both gentoo and liguros.