Tweak rule for bazarr
repology/repology-rules pull request #876
Opened 2024-10-27 08:57 UTC by txtsd

2024-10-28 12:11 UTC, AMDmi3 requested changes

2024-10-28 12:11 UTC, AMDmi3 commented on 800.renames-and-merges/b.yaml
> +- { setname: bazarr,                   name: $0-beta, devel: true }
`nolegacy` should stay and you don't need `devel` as long is it's versioned properly (`XbetaY`)

2024-11-25 16:29 UTC, AMDmi3 commented
Timeout

2024-11-25 16:29 UTC, closed without merging

2024-11-26 02:18 UTC, txtsd commented
Sorry completely forgot about these