Split mp3cat
repology/repology-rules pull request #886
Opened 2024-11-29 23:57 UTC by TheRealKeto

There seems to be some ambiguity between two projects with the same name. `mp3cat` was originally written by Tom Clegg, yet there exists a different project written by someone else with the same name, only it has a different function and is written in Go.

For Termux, Repology already recognizes the correct name of the package (`mp3cat-go`), so this serves as a change that will split the packages in two, which should also fix issues regarding versions, which also differ (0.5 vs. 4.2.2)

2024-11-30 23:11 UTC, AMDmi3 commented
You're missing a split rule to assign unique name for another kind of mp3cat. You also need to merge mp3cat-go into mp3cat so all mp3cats go through the same split rules.

2024-11-30 23:15 UTC, TheRealKeto commented
To clarify, the other kind of mp3cat rightfully has the name `mp3cat`. This is more to clarify that the package from the AUR with the same name belongs outside that category and should instread be renamed to `mp3cat-go`.

In any case, I've also thought about renaming all packages - Tom Clegg's `mp3cat` -> `mp3cat-tomclegg`; `mp3cat-go` -> `mp3cat-dmulholl`. Let me know which works best for Repology!

2024-11-30 23:39 UTC, AMDmi3 commented
`mp3cat-tomclegg` and `mp3cat-dmulholl` look good.

2024-12-01 20:51 UTC, AMDmi3 requested changes

2024-12-01 20:51 UTC, AMDmi3 commented on 850.split-ambiguities/m.yaml
> +- { name: mp3cat-go, wwwpart: dmulholl, setname: mp3cat-dmulholl }
That goes into 800 ruleset, just a single rule is needed.

2024-12-03 01:18 UTC, AMDmi3 approved these changes

2024-12-03 01:18 UTC, merged